// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("newrelic")
	ScopeName = "otelcol/newrelic"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
